import type { Materials, MueblesGallery } from "../types/index.types";

export const materials: Materials[] = [
  {
    id: 1,
    img: "/materiales/Chromix-blanco.webp",
    color: ["Blanco", "Gris claro", "Gris"],
    alt: "Chromix blanco",
    title: "Chromix blanco",
  },
  {
    id: 2,
    img: "/materiales/Chromix-plata.webp",
    color: ["Plata", "Gris oscuro", "Gris"],
    alt: "Chromix plata",
    title: "Chromix plata",
  },
  {
    id: 3,
    img: "/materiales/Roble-Davos-natural.webp",
    color: ["Madera natural", "Roble"],
    alt: "Roble Davos Natural",
    title: "Roble Davos Natural",
  },
  {
    id: 4,
    img: "/materiales/Roble-de-Nebraska-gris.webp",
    color: ["Madera natural", "Roble"],
    alt: "Roble de Nebraska Gris",
    title: "Roble de Nebraska Gris",
  },
  {
    id: 5,
    img: "/materiales/Roble-de-Nebraska-natural.webp",
    color: ["Madera natural", "Roble"],
    alt: "Roble de Nebraska Natural",
    title: "Roble de Nebraska Natural",
  },
  {
    id: 6,
    img: "/materiales/Hickory-natural.webp",
    color: ["Hickory", "Madera natural"],
    alt: "Hickory Natural",
    title: "Hickory Natural",
  },
  {
    id: 7,
    img: "/materiales/Hormigón-Chicago-gris-oscuro.webp",
    color: ["Gris", "Gris oscuro", "Hormigón"],
    alt: "Hormigón Chicago Gris Oscuro",
    title: "Hormigón Chicago Gris Oscuro",
  },
  {
    id: 8,
    img: "/materiales/Nogal-del-Pacífico-natural.webp",
    color: ["Madera natural", "Nogal"],
    alt: "Nogal del Pacífico Natural",
    title: "Nogal del Pacífico Natural",
  },
  {
    id: 9,
    img: "/materiales/Pietra-Grigia-negro.webp",
    color: ["Negro", "Cerámico"],
    alt: "Pietra Grigia Negro",
    title: "Pietra Grigia Negro",
  },
  {
    id: 10,
    img: "/materiales/Blanco.webp",
    color: ["Blanco", "Color plano"],
    alt: "Blanco",
    title: "Blanco",
  },
  {
    id: 11,
    img: "/materiales/Negro.webp",
    color: ["Negro", "Color plano"],
    alt: "Negro",
    title: "Negro",
  },
  {
    id: 12,
    img: "/materiales/Gris-arcilla.webp",
    color: ["Gris", "Color plano"],
    alt: "Gris Arcilla",
    title: "Gris Arcilla",
  },
  {
    id: 13,
    img: "/materiales/Gris-macadán.webp",
    color: ["Gris", "Color plano"],
    alt: "Gris Macadán",
    title: "Gris Macadán",
  },
  {
    id: 14,
    img: "/materiales/Gris-sombra.webp",
    color: ["Gris", "Color plano"],
    alt: "Gris Sombra",
    title: "Gris Sombra",
  },
];

export const muebles: MueblesGallery[] = [
  {
    // img: "/images/gallery/1.jpg",
    id: 1,
    img: "/muebles/mueble-1.jpg",
    alt: "Mueble 1",
    title: "Mueble 1",
    description: "Descripción del mueble 1",
    category: "Rack TV",
    materials: ["Nebraska", "Nogal", "Blanco"],
  },
  {
    id: 2,
    img: "/muebles/mueble-2.jpg",
    alt: "Mueble 2",
    title: "Mueble 2",
    description: "Descripción del mueble 2",
    category: "Sofá",
    materials: ["Cuero", "Tela"],
  },
  {
    id: 3,
    img: "/muebles/mueble-3.jpg",
    alt: "Mueble 3",
    title: "Mueble 3",
    description: "Descripción del mueble 3",
    category: "Mesa de centro",
    materials: ["Madera", "Vidrio"],
  },
  {
    id: 4,
    img: "/muebles/mueble-4.jpg",
    alt: "Mueble 4",
    title: "Mueble 4",
    description: "Descripción del mueble 4",
    category: "Mesa de centro",
    materials: ["Madera", "Vidrio"],
  },
  {
    id: 5,
    img: "/muebles/mueble-5.jpg",
    alt: "Mueble 5",
    title: "Mueble 5",
    description: "Descripción del mueble 5",
    category: "Mesa de centro",
    materials: ["Madera", "Vidrio"],
  },
  {
    id: 6,
    img: "/muebles/mueble-6.jpg",
    alt: "Mueble 6",
    title: "Mueble 6",
    description: "Descripción del mueble 6",
    category: "Mesa de centro",
    materials: ["Madera", "Vidrio"],
  },
];
